<script setup lang="ts">
import { computed } from 'vue';
import AdjustmentEditor from './AdjustmentEditor.vue';
import Icon from './Icon.vue';
const props=defineProps<{e:any;mode:string;tool:string;disabled:boolean;selected?:any;color:string;size:number;opacity:number;target:string}>();
const emit=defineEmits(['color','size','opacity','target','edit']);const l=computed(()=>props.e.labels);
const aligns=[['left','alignLeft'],['hcenter','alignHcenter'],['right','alignRight'],['top','alignTop'],['vcenter','alignVcenter'],['bottom','alignBottom'],['hspread','hspread'],['vspread','vspread'],['hgap','hgap'],['vgap','vgap']];
const brush=computed(()=>['brush','eraser','healing','clone','smear'].includes(props.tool));
const filterFields=computed(()=>({ 'Gaussian Blur':['radius'],'Motion Blur':['angle','distance'],'Add Noise':['amount'],'Sharpen':['radius','amount'],'Mosaic':['size'],'Dither':['levels'],'Vignette':['amount'],'Bloom / Glow':['radius','amount'],'Tonal Contrast':['radius','amount'],'Lens Correction':['distortion'],'Camera Raw Filter':['exposure','contrast','saturation','temperature'],'Remove Background':['tolerance'],'Content-Aware Fill':[],'Exposure':[] } as Record<string,string[]>)[props.e.filter.kind]??[]);
function value(event:Event){return (event.target as HTMLInputElement).value;}
</script>
<template>
  <template v-if="mode==='options'">
    <template v-if="['marquee','lasso','wand'].includes(tool)">
      <select v-model="e.options.combine" :aria-label="l.selection" :disabled="disabled"><option v-for="key in ['replace','add','subtract','intersect']" :key="key" :value="key">{{ l[key] }}</option></select>
      <select v-if="tool==='marquee'" v-model="e.options.marquee" :aria-label="l.marquee"><option value="rectangle">{{ l.rectangle }}</option><option value="ellipse">{{ l.ellipse }}</option></select>
    </template>
    <template v-if="['wand','bucket','eyedropper'].includes(tool)">
      <label v-if="tool!=='eyedropper'">{{ l.tolerance }}<input type="number" min="0" max="255" v-model.number="e.options.tolerance"></label>
      <label v-if="tool!=='eyedropper'"><input type="checkbox" v-model="e.options.contiguous">{{ l.contiguous }}</label>
      <label><input type="checkbox" v-model="e.options.sampleAll">{{ l.sampleAll }}</label>
    </template>
    <template v-if="brush || ['bucket','gradient'].includes(tool)">
      <label v-if="brush">{{ l.brushSize }}<input data-testid="brush-size" type="number" min="1" max="500" :value="size" :disabled="disabled" @change="emit('size',Number(value($event)))"></label>
      <label>{{ l.brushOpacity }}<input data-testid="brush-opacity" type="number" min="0" max="100" :value="opacity" :disabled="disabled" @change="emit('opacity',Number(value($event)))"></label>
      <template v-if="brush"><label>{{ l.hardness }}<input type="number" min="0" max="100" v-model.number="e.options.hardness"></label><label>{{ l.spacing }}<input type="number" min="1" max="200" v-model.number="e.options.spacing"></label><label><input type="checkbox" v-model="e.options.pressure">{{ l.pressure }}</label>
        <select v-model="e.options.symmetry" :aria-label="l.symmetry"><option v-for="key in ['none','horizontal','vertical','both','radial']" :key="key" :value="key">{{ l[key] }}</option></select><label v-if="e.options.symmetry==='radial'">{{ l.sectors }}<input type="number" min="2" max="16" v-model.number="e.options.sectors"></label>
      </template>
      <select :value="target" :disabled="disabled || !selected?.maskFile" :aria-label="l.paintTarget" @change="emit('target',value($event))"><option value="content">{{ l.content }}</option><option value="mask">{{ l.mask }}</option></select>
    </template>
    <select v-if="tool==='smear'" v-model="e.options.smear" :aria-label="l.smear"><option v-for="key in ['blur','smudge','liquify']" :key="key" :value="key">{{ l[key] }}</option></select>
    <small v-if="tool==='clone'">{{ e.cloneSource?l.cloneSet:l.cloneHint }}</small><small v-if="tool==='healing'">{{ l.healingHint }}</small>
    <template v-if="tool==='gradient'"><select :value="e.options.radial?'radial':'linear'" :aria-label="l.gradient" @change="e.options.radial=value($event)==='radial'"><option value="linear">{{ l.linear }}</option><option value="radial">{{ l.radialGradient }}</option></select><label><input type="checkbox" v-model="e.options.reverse">{{ l.reverse }}</label><label><input type="checkbox" v-model="e.options.transparent">{{ l.transparent }}</label></template>
    <template v-if="tool==='shape'"><select v-model="e.options.shape" :aria-label="l.shape"><option value="Rectangle">{{ l.rectangle }}</option><option value="Ellipse">{{ l.ellipse }}</option><option value="Line">{{ l.line }}</option></select><label>{{ l.corner }}<input type="number" min="0" max="30000" v-model.number="e.options.corner"></label><label>{{ l.lineWidth }}<input type="number" min="0" max="2000" v-model.number="e.options.lineWidth"></label><button v-if="selected?.shape" @click="e.openStyle('shape')">{{ l.editStyle }}</button></template>
    <button v-if="tool==='type'" :disabled="disabled" @click="e.openStyle('text')">{{ l.editStyle }}</button>
    <template v-if="tool==='crop'"><span>{{ e.cropBox?Math.round(e.cropBox.w)+' × '+Math.round(e.cropBox.h):l.crop }}</span><button :disabled="!e.cropBox" data-testid="apply-crop" @click="e.applyCrop()">{{ l.apply }}</button><button :disabled="!e.cropBox" @click="e.cancel()">{{ l.cancel }}</button><button @click="e.cropSelection()">{{ l.cropSelection }}</button></template>
    <template v-if="tool==='move'"><label><input type="checkbox" v-model="e.options.autoSelect">{{ l.autoSelect }}</label><label><input type="checkbox" v-model="e.options.snap">{{ l.snap }}</label></template>
  </template>
  <div v-else-if="mode==='panel'" class="complete-panel">
    <details class="property-section" open><summary>{{ l.arrange }} <small>{{ e.ids.length }}</small></summary><label>{{ l.reference }}<select v-model="e.options.reference"><option v-for="key in ['selection','canvas','keyObject']" :key="key" :value="key">{{ key==='selection'?l.selected:l[key] }}</option></select></label><div class="arrange-grid"><button v-for="[op,key] in aligns" :key="op" :disabled="disabled || !e.ids.length" :title="l[key]" @click="e.align(op)">{{ l[key] }}</button></div><div class="button-row"><button :disabled="disabled || !e.ids.length" @click="e.group()">{{ l.group }}</button><button :disabled="disabled || !selected?.isGroup" @click="emit('edit',{kind:'ungroup'})">{{ l.ungroup }}</button></div></details>
    <details class="property-section"><summary>{{ l.selection }}</summary><div class="button-row"><button v-for="key in ['all','none','invert']" :key="key" :disabled="disabled" @click="e.selection(key)">{{ key==='none'?l.deselect:l[key] }}</button></div><label>{{ l.selectionAmount }}<input type="number" min="0" max="500" v-model.number="e.options.selectionAmount"></label><div class="button-row"><button v-for="key in ['expand','contract','feather']" :key="key" :disabled="disabled" @click="e.selection(key)">{{ l[key] }}</button></div><div class="button-row"><button :disabled="disabled || !selected?.imageFile" @click="e.fill()">{{ l.fill }}</button><button :disabled="disabled || !selected?.imageFile" @click="e.fill('clear')">{{ l.clear }}</button><button :disabled="disabled || !selected || selected.maskFile" @click="emit('edit',{kind:'selectionMask'})">{{ l.selectionMask }}</button></div></details>
    <details class="property-section"><summary>{{ l.imageSize }}</summary><div class="button-row"><button :disabled="disabled" data-testid="canvas-size" @click="e.openSize('canvasSize')">{{ l.canvasSize }}</button><button :disabled="disabled" data-testid="image-size" @click="e.openSize('imageSize')">{{ l.imageSize }}</button><button :disabled="disabled" @click="e.trim()">{{ l.trim }}</button></div></details>
    <details class="property-section" v-if="selected"><summary>{{ l.sessionLocks }}</summary><label v-for="[key,name] in [['content','lockContent'],['position','lockPosition'],['appearance','lockAppearance'],['alpha','lockAlpha']]" :key="key"><input type="checkbox" :checked="e.lock[key]" :disabled="disabled" @change="e.setLock(key,($event.target as HTMLInputElement).checked)">{{ l[name] }}</label></details>
    <details class="property-section"><summary>{{ l.guide }}</summary><div class="button-row"><label><input type="checkbox" v-model="e.options.grid">{{ l.grid }}</label><label><input type="checkbox" v-model="e.options.snap">{{ l.snap }}</label></div><label>{{ l.guideAxis }}<select v-model="e.options.guideAxis"><option value="vertical">{{ l.verticalGuide }}</option><option value="horizontal">{{ l.horizontalGuide }}</option></select></label><label>{{ l.guidePosition }}<input type="number" min="-300000" max="300000" v-model.number="e.options.guidePosition"></label><div class="button-row"><button :disabled="disabled" @click="e.addGuide()">{{ l.addGuide }}</button><button :disabled="disabled" @click="e.clearGuides()">{{ l.clearGuides }}</button></div></details>
    <div class="button-row"><button :disabled="disabled || !selected?.imageFile" data-testid="open-filter" @click="e.openFilter()">{{ l.filter }}</button><button v-if="selected?.text||selected?.shape" :disabled="disabled" @click="e.openStyle(selected.text?'text':'shape')">{{ l.editStyle }}</button><button :disabled="disabled || !selected?.imageFile" @click="emit('edit',{kind:'rasterize'})">{{ l.rasterize }}</button><button :disabled="disabled || !selected?.maskFile || !selected.imageFile" @click="emit('edit',{kind:'applyMask'})">{{ l.applyMask }}</button></div>
    <div class="button-row"><button :disabled="disabled || !e.ids.length" @click="e.duplicate()">{{ l.duplicate }}</button><button :disabled="disabled || e.ids.length<2" data-testid="merge-layers" @click="e.merge()">{{ l.merge }}</button><button :disabled="disabled" @click="e.merge(true)">{{ l.flatten }}</button></div>
  </div>
  <div v-else-if="mode==='dialogs' && e.modal" class="modal-shade" @click.self="e.closeModal()">
    <form class="dialog editor-dialog" role="dialog" aria-modal="true" :aria-label="l[e.modal==='text'?'text':e.modal==='shape'?'shape':e.modal==='filter'?'filter':e.modal]" @submit.prevent="e.modal==='filter'?e.applyFilter():['text','shape'].includes(e.modal)?e.applyStyle():e.applySize()">
      <h2>{{ l[e.modal] }}</h2>
      <template v-if="['canvasSize','imageSize'].includes(e.modal)"><div class="new-dimensions"><label>{{ l.width }}<input type="number" min="1" max="30000" v-model.number="e.size.width" required></label><button class="icon-button" type="button" :title="l.swap" @click="[e.size.width,e.size.height]=[e.size.height,e.size.width]"><Icon name="swap"/></button><label>{{ l.height }}<input type="number" min="1" max="30000" v-model.number="e.size.height" required></label></div><label v-if="e.modal==='canvasSize'">{{ l.anchor }}<select v-model="e.size.anchor"><option v-for="key in ['topLeft','middle','bottomRight']" :key="key" :value="key">{{ l[key] }}</option></select></label><label v-else>{{ l.resample }}<select :value="e.size.nearest?'nearest':'bilinear'" @change="e.size.nearest=value($event)==='nearest'"><option value="nearest">{{ l.nearest }}</option><option value="bilinear">{{ l.bilinear }}</option></select></label></template>
      <template v-else-if="e.modal==='text'"><label>{{ l.content }}<textarea :ref="(el:any)=>e.textArea=el" v-model="e.text.content" data-testid="text-content" rows="5" maxlength="100000" @select="e.rememberRange()" @keyup="e.rememberRange()" @mouseup="e.rememberRange()"></textarea></label><div class="style-fields"><label>{{ l.font }}<input v-model="e.text.fontName" maxlength="200" list="font-list"></label><datalist id="font-list"><option v-for="font in ['ArialMT','Segoe UI','Microsoft YaHei','SimSun','SimHei','Times New Roman','Consolas']" :key="font">{{ font }}</option></datalist><label>{{ l.fontSize }}<input type="number" min="1" max="2000" v-model.number="e.text.fontSize"></label><label>{{ l.tracking }}<input type="number" min="-100" max="1000" v-model.number="e.text.tracking"></label><label>{{ l.leading }}<input type="number" min="0" max="5000" v-model.number="e.text.leading"></label><label>{{ l.width }}<input type="number" min="16" max="30000" v-model.number="e.text.boxSize[0]"></label><label>{{ l.height }}<input type="number" min="16" max="30000" v-model.number="e.text.boxSize[1]"></label><label>{{ l.alignment }}<select v-model="e.text.alignment"><option value="Left">{{ l.left }}</option><option value="Center">{{ l.center }}</option><option value="Right">{{ l.right }}</option></select></label><label>{{ l.foreground }}<input type="color" :value="'#'+['red','green','blue'].map(k=>Math.round(e.text[k]*255).toString(16).padStart(2,'0')).join('')" @input="['red','green','blue'].forEach((k,i)=>e.text[k]=parseInt(value($event).slice(i*2+1,i*2+3),16)/255)"></label></div><div class="button-row"><button type="button" @click="e.styleRange('color')">{{ l.rangeColor }}</button><button type="button" @click="e.styleRange('font')">{{ l.rangeFont }}</button></div><small>{{ l.fontNote }}</small></template>
      <template v-else-if="e.modal==='shape'"><div class="style-fields"><label>{{ l.shape }}<select v-model="e.shape.kind"><option value="Rectangle">{{ l.rectangle }}</option><option value="Ellipse">{{ l.ellipse }}</option><option value="Line">{{ l.line }}</option></select></label><label>{{ l.width }}<input type="number" min="1" max="30000" v-model.number="e.size.width"></label><label>{{ l.height }}<input type="number" min="1" max="30000" v-model.number="e.size.height"></label><label>{{ l.corner }}<input type="number" min="0" max="30000" v-model.number="e.shape.cornerRadius"></label><label>{{ l.lineWidth }}<input type="number" min="0" max="2000" v-model.number="e.shape.lineWidth"></label><label>{{ l.foreground }}<input type="color" :value="'#'+['red','green','blue'].map(k=>Math.round(e.shape[k]*255).toString(16).padStart(2,'0')).join('')" @input="['red','green','blue'].forEach((k,i)=>e.shape[k]=parseInt(value($event).slice(i*2+1,i*2+3),16)/255)"></label></div></template>
      <template v-else-if="e.modal==='filter'"><select v-model="e.filter.kind" data-testid="filter-kind" :aria-label="l.filter"><option v-for="(kind,i) in e.filters" :key="kind" :value="kind">{{ l.filters[i] }}</option></select><div class="style-fields"><label v-for="key in filterFields" :key="key">{{ l[key] }}<input type="number" v-model.number="e.filter[key]" :min="['exposure','contrast','saturation','temperature','distortion','angle'].includes(key)?-100:0" :max="['contrast','saturation','temperature','distortion','amount'].includes(key)?100:key==='exposure'?10:key==='size'?500:key==='radius'?200:key==='tolerance'?255:key==='exposure'?10:1000"></label></div><AdjustmentEditor v-if="['Curves','Exposure','Gradient Map','Grain','Black &amp; White','Color Balance'].includes(e.filter.kind)" :value="e.filter" :zh="l.text==='文字'" :disabled="e.previewBusy" @edit="e.filterParameter($event)"/><small v-if="e.filter.kind==='Remove Background'">{{ l.backgroundNote }}</small><small v-if="e.filter.kind==='Content-Aware Fill'">{{ l.inpaintNote }}</small></template>
      <template v-if="['text','shape','filter'].includes(e.modal)"><div class="button-row"><button type="button" :disabled="e.previewBusy" data-testid="update-preview" @click="e.updatePreview()">{{ l.preview }}</button></div><div class="editor-preview"><img v-if="e.previewURL" :src="e.previewURL" :alt="l.preview"><span v-if="e.previewBusy">…</span></div></template>
      <div class="button-row dialog-actions"><button type="button" @click="e.closeModal()">{{ l.cancel }}</button><button class="primary" type="submit" data-testid="apply-editor" :disabled="e.previewBusy || (e.modal==='text' && !e.text.content)">{{ l.apply }}</button></div>
    </form>
  </div>
</template>
