export const fullEditor = {
  'zh-Hans': {
    brushSize:'大小',brushOpacity:'不透明度',paintTarget:'绘画目标',mask:'蒙版',marquee:'选框',lasso:'套索',wand:'魔棒',crop:'裁剪',healing:'污点修复',clone:'仿制图章',smear:'涂抹',gradient:'渐变',bucket:'油漆桶',shape:'形状',type:'文字',eyedropper:'取色',zoom:'缩放',
    replace:'替换',add:'添加',subtract:'减去',intersect:'交集',rectangle:'矩形',ellipse:'椭圆',line:'直线',tolerance:'容差',contiguous:'连续区域',sampleAll:'取样所有图层',hardness:'硬度',spacing:'间距',pressure:'压感',symmetry:'对称',none:'无',horizontal:'左右镜像',vertical:'上下镜像',both:'双轴镜像',radial:'径向',sectors:'份数',blur:'模糊',smudge:'涂抹',liquify:'推移',cloneHint:'Alt 单击设置来源；拖动复制',cloneSet:'来源已设置',healingHint:'邻近纹理修复',linear:'线性',radialGradient:'径向',reverse:'反向',transparent:'渐变至透明',background:'背景色',foreground:'前景色',swap:'交换前景色与背景色',defaults:'恢复黑白',corner:'圆角',lineWidth:'线宽',editStyle:'编辑文字／形状',
    apply:'应用',cancel:'取消',text:'文字',content:'内容',font:'字体',fontSize:'字号',tracking:'字距',leading:'行距（0 为自动）',alignment:'对齐',left:'左对齐',center:'居中',right:'右对齐',width:'宽度',height:'高度',rangeColor:'为选中文字设颜色',rangeFont:'为选中文字设字体',fontNote:'使用本机字体。缺失字体会用后备字体重新排版；应用前请确认预览。',
    selection:'选区',all:'全选',deselect:'取消选区',invert:'反选',expand:'扩展',contract:'收缩',feather:'羽化',selectionAmount:'选区调整（像素）',fill:'填充前景色',clear:'清除',selectionMask:'选区转蒙版',cropSelection:'裁剪到选区',
    canvasSize:'画布尺寸',imageSize:'图像尺寸',trim:'修剪透明边缘',resample:'重采样',nearest:'最近邻',bilinear:'双线性',anchor:'锚点',topLeft:'左上',middle:'中心',bottomRight:'右下',
    arrange:'对齐／分布',reference:'参照',selected:'所选图层',canvas:'画布',keyObject:'关键图层',alignLeft:'左对齐',alignHcenter:'水平居中',alignRight:'右对齐',alignTop:'顶对齐',alignVcenter:'垂直居中',alignBottom:'底对齐',hspread:'水平中心分布',vspread:'垂直中心分布',hgap:'水平间距分布',vgap:'垂直间距分布',group:'编组',ungroup:'解组',duplicate:'复制图层',merge:'合并所选图层',flatten:'拼合图像',rasterize:'栅格化',applyMask:'应用蒙版',lockContent:'锁定内容',lockPosition:'锁定位置',lockAppearance:'锁定外观',lockAlpha:'锁定透明度',sessionLocks:'锁定仅在本次打开中有效',
    filter:'滤镜',preview:'预览',radius:'半径',amount:'强度',size:'块大小',angle:'角度',distance:'距离',levels:'色阶数',exposure:'曝光',contrast:'对比度',saturation:'饱和度',temperature:'色温',distortion:'畸变',backgroundNote:'按边缘颜色移除背景，适用于简单背景。',inpaintNote:'使用邻近像素修补选区；复杂结构可能需要仿制图章继续修整。',
    filters:['高斯模糊','动感模糊','添加杂色','锐化','马赛克','抖色','暗角','辉光','色调对比','镜头校正','相机原始滤镜','移除背景','内容修补','曲线','曝光','渐变映射','颗粒','黑白','色彩平衡','反相','去色'],
    copy:'复制',copyMerged:'合并复制',cut:'剪切',paste:'粘贴',autoSelect:'自动选择',grid:'网格',snap:'吸附',guide:'参考线',guideAxis:'方向',guidePosition:'位置',addGuide:'添加参考线',clearGuides:'清除参考线',verticalGuide:'垂直',horizontalGuide:'水平',rotate:'旋转',resize:'调整大小',noSelection:'请先创建选区',sourceNeeded:'先 Alt 单击设置仿制来源',locked:'图层已锁定',limit:'超出图像或操作预算',
  },
  en: {
    brushSize:'Size',brushOpacity:'Opacity',paintTarget:'Paint target',mask:'Mask',marquee:'Marquee',lasso:'Lasso',wand:'Magic Wand',crop:'Crop',healing:'Spot Healing',clone:'Clone Stamp',smear:'Smear',gradient:'Gradient',bucket:'Paint Bucket',shape:'Shape',type:'Text',eyedropper:'Eyedropper',zoom:'Zoom',
    replace:'Replace',add:'Add',subtract:'Subtract',intersect:'Intersect',rectangle:'Rectangle',ellipse:'Ellipse',line:'Line',tolerance:'Tolerance',contiguous:'Contiguous',sampleAll:'Sample all layers',hardness:'Hardness',spacing:'Spacing',pressure:'Pressure',symmetry:'Symmetry',none:'None',horizontal:'Mirror horizontally',vertical:'Mirror vertically',both:'Mirror both axes',radial:'Radial',sectors:'Sectors',blur:'Blur',smudge:'Smudge',liquify:'Push',cloneHint:'Alt-click to set source; drag to clone',cloneSet:'Source set',healingHint:'Repair from nearby texture',linear:'Linear',radialGradient:'Radial',reverse:'Reverse',transparent:'Fade to transparent',background:'Background color',foreground:'Foreground color',swap:'Swap foreground and background',defaults:'Default black and white',corner:'Corner radius',lineWidth:'Line width',editStyle:'Edit text / shape',
    apply:'Apply',cancel:'Cancel',text:'Text',content:'Content',font:'Font',fontSize:'Font size',tracking:'Tracking',leading:'Leading (0 = automatic)',alignment:'Alignment',left:'Left',center:'Center',right:'Right',width:'Width',height:'Height',rangeColor:'Color selected text',rangeFont:'Font for selected text',fontNote:'Uses installed fonts. Missing fonts are reflowed using a fallback. Check the preview before applying.',
    selection:'Selection',all:'Select all',deselect:'Deselect',invert:'Invert selection',expand:'Expand',contract:'Contract',feather:'Feather',selectionAmount:'Selection adjustment (pixels)',fill:'Fill foreground',clear:'Clear',selectionMask:'Selection to mask',cropSelection:'Crop to selection',
    canvasSize:'Canvas size',imageSize:'Image size',trim:'Trim transparent edges',resample:'Resampling',nearest:'Nearest neighbor',bilinear:'Bilinear',anchor:'Anchor',topLeft:'Top left',middle:'Center',bottomRight:'Bottom right',
    arrange:'Align / distribute',reference:'Reference',selected:'Selected layers',canvas:'Canvas',keyObject:'Key layer',alignLeft:'Align left',alignHcenter:'Align horizontal centers',alignRight:'Align right',alignTop:'Align top',alignVcenter:'Align vertical centers',alignBottom:'Align bottom',hspread:'Distribute horizontal centers',vspread:'Distribute vertical centers',hgap:'Distribute horizontal gaps',vgap:'Distribute vertical gaps',group:'Group',ungroup:'Ungroup',duplicate:'Duplicate layers',merge:'Merge selected layers',flatten:'Flatten image',rasterize:'Rasterize',applyMask:'Apply mask',lockContent:'Lock content',lockPosition:'Lock position',lockAppearance:'Lock appearance',lockAlpha:'Lock transparency',sessionLocks:'Locks apply only while this document is open',
    filter:'Filter',preview:'Preview',radius:'Radius',amount:'Amount',size:'Block size',angle:'Angle',distance:'Distance',levels:'Levels',exposure:'Exposure',contrast:'Contrast',saturation:'Saturation',temperature:'Temperature',distortion:'Distortion',backgroundNote:'Removes a background by its edge color. Best for simple backgrounds.',inpaintNote:'Repairs the selection using nearby pixels. Complex structures may need the Clone Stamp.',
    filters:['Gaussian Blur','Motion Blur','Add Noise','Sharpen','Mosaic','Dither','Vignette','Bloom / Glow','Tonal Contrast','Lens Correction','Camera Raw Filter','Remove Background','Content Repair','Curves','Exposure','Gradient Map','Grain','Black & White','Color Balance','Invert','Desaturate'],
    copy:'Copy',copyMerged:'Copy merged',cut:'Cut',paste:'Paste',autoSelect:'Auto select',grid:'Grid',snap:'Snap',guide:'Guide',guideAxis:'Direction',guidePosition:'Position',addGuide:'Add guide',clearGuides:'Clear guides',verticalGuide:'Vertical',horizontalGuide:'Horizontal',rotate:'Rotate',resize:'Resize',noSelection:'Create a selection first',sourceNeeded:'Alt-click to set the clone source first',locked:'This layer is locked',limit:'Image or operation budget exceeded',
  }
};
