import { computed, reactive, ref, watch, nextTick, type Ref } from 'vue';
import { fullEditor } from './editor-labels';
import { bounds, union, toLocal, maskBounds, selectionCoverage } from '../../../packages/comp-bridge/editor-math.mjs';
import { FILTERS } from '../../../packages/comp-bridge/raster-tools.mjs';
import { makeCanvas, pngBytes, placedImage, createPreviewRenderer } from '../../../packages/editor-adapter/render';
import { renderText, renderShape, rangeStyle, remapRuns } from '../../../packages/editor-adapter/styled-layers';
import type { ViewerProject, LayerRow, Language, OpenResult } from './types';
type Context={project:Ref<ViewerProject|undefined>;selected:Ref<LayerRow|undefined>;tool:Ref<string>;color:Ref<string>;brushSize:Ref<number>;brushOpacity:Ref<number>;paintTarget:Ref<string>;painting:Ref<boolean>;editable:Ref<boolean>;language:Ref<Language>;canvas:Ref<HTMLCanvasElement|undefined>;overlay:Ref<HTMLCanvasElement|undefined>;artboard:Ref<HTMLDivElement|undefined>;stage:Ref<HTMLDivElement|undefined>;zoom:Ref<number>;error:Ref<string>;execute:(op:Record<string,unknown>,p?:ViewerProject)=>Promise<void>|undefined;receive:(result:OpenResult)=>Promise<void>;history:(direction:string)=>unknown;scale:(factor:number)=>void};
export const TOOL_LIST=['move','marquee','lasso','wand','crop','brush','eraser','healing','clone','smear','gradient','bucket','shape','type','eyedropper','pan','zoom'];
export const TOOL_KEYS:Record<string,string>={move:'V',marquee:'M',lasso:'L',wand:'W',crop:'C',brush:'B',eraser:'E',healing:'J',clone:'S',smear:'R',gradient:'G',bucket:'K',shape:'U',type:'T',eyedropper:'I',pan:'H',zoom:'Z'};
const colors=(hex:string)=>[1,3,5].map(i=>parseInt(hex.slice(i,i+2),16));
const clone=<T>(v:T):T=>JSON.parse(JSON.stringify(v));
export function useCompleteEditor(c:Context){
  const labels=computed(()=>fullEditor[c.language.value]),ids=ref<string[]>([]),background=ref('#ffffff');
  const options=reactive({combine:'replace',marquee:'rectangle',tolerance:24,contiguous:true,sampleAll:true,hardness:100,spacing:18,pressure:true,symmetry:'none',sectors:6,smear:'blur',radial:false,reverse:false,transparent:false,shape:'Rectangle',corner:0,lineWidth:8,autoSelect:false,grid:false,snap:false,selectionAmount:4,reference:'selection',guideAxis:'vertical',guidePosition:100});
  const modal=ref(''),size=reactive({width:1920,height:1080,anchor:'middle',nearest:false}),text=reactive<Record<string,any>>({content:'',fontName:'ArialMT',fontSize:48,red:0,green:0,blue:0,alignment:'Left',tracking:0,leading:0,boxSize:[480,240],colorRuns:[],fontRuns:[]});
  const shape=reactive<Record<string,any>>({kind:'Rectangle',red:0,green:0,blue:0,cornerRadius:0,lineWidth:8,start:[0,0],end:[1,1]});
  const filter=reactive<Record<string,any>>({kind:'Gaussian Blur',radius:4,amount:50,size:16,angle:0,distance:10,levels:4,exposure:0,contrast:0,saturation:0,temperature:0,distortion:0,tolerance:28});
  const previewURL=ref(''),previewBusy=ref(false),textArea=ref<HTMLTextAreaElement>(),cloneSource=ref<[number,number]>(),cropBox=ref<{x:number;y:number;w:number;h:number}>();
  let styledID:string|undefined,styleOrigin:[number,number]=[0,0],styleOwner:ViewerProject|undefined,originalContent='',range:[number,number]=[0,0],previewEpoch=0,previewWorker:Worker|undefined,previewBlob:string|undefined;
  type Drag={p:ViewerProject;row?:LayerRow;transform?:LayerRow['transform'];params:typeof options;target:string;pointer:number;tool:string;start:[number,number];current:[number,number];points:number[][];settings:Record<string,any>;ids:string[];handle?:string};let drag:Drag|undefined,applying=false;
  const lock=computed(()=>c.project.value?.locks?.[c.selected.value?.id??'']??{});
  const selectedRows=computed(()=>c.project.value?.analysis.rows.filter(l=>ids.value.includes(l.id))??[]);
  const selectionTransform=computed(()=>{const p=c.project.value,row=c.selected.value;if(!p||!row)return undefined;if(ids.value.length<=1&&!row.isGroup)return row.transform;const set=new Set(roots(p,ids.value));for(let n=0;n<64;n++)for(const l of p.analysis.rows)if(l.parentID&&set.has(l.parentID))set.add(l.id);const box=union(p.analysis.rows.filter(l=>set.has(l.id)&&l.imageFile).map(l=>bounds(l.transform)));return {origin:[box.x,box.y] as [number,number],size:[Math.max(1,box.w),Math.max(1,box.h)] as [number,number],rotation:0,flipX:false,flipY:false,sampling:'High quality'};});
  const selectedRect=computed(()=>{const row=c.selected.value;return row?bounds(row.transform):undefined;});
  function valid(p?:ViewerProject){return !!p&&p.id===c.project.value?.id&&p.revision===c.project.value.revision;}
  function roots(p:ViewerProject,list:string[]){return list.filter(id=>{let l=p.analysis.rows.find(v=>v.id===id);for(let n=0;l?.parentID&&n<64;n++){if(list.includes(l.parentID))return false;l=p.analysis.rows.find(v=>v.id===l!.parentID);}return true;});}
  function select(row:LayerRow,event?:MouseEvent){const existing=ids.value;if(event?.shiftKey&&c.selected.value){const rows=c.project.value!.analysis.rows,a=rows.findIndex(l=>l.id===c.selected.value!.id),b=rows.findIndex(l=>l.id===row.id);ids.value=rows.slice(Math.min(a,b),Math.max(a,b)+1).map(l=>l.id);}else if(event?.ctrlKey||event?.metaKey)ids.value=existing.includes(row.id)?existing.filter(v=>v!==row.id):[...existing,row.id];else ids.value=[row.id];c.selected.value=row;}
  watch(()=>[c.project.value?.id,c.project.value?.revision],(now,old)=>{cancel();const p=c.project.value;if(!p){ids.value=[];return;}ids.value=ids.value.filter(id=>p.analysis.rows.some(l=>l.id===id));if(c.selected.value&&!ids.value.includes(c.selected.value.id))ids.value=[c.selected.value.id];if(now[0]!==old?.[0])cloneSource.value=undefined;if(modal.value)closeModal();nextTick(drawSelection);});
  watch(()=>c.selected.value?.id,(now,old)=>{if(now!==old)cloneSource.value=undefined;});
  function point(e:PointerEvent):[number,number]{const box=c.artboard.value!.getBoundingClientRect();return [(e.clientX-box.left)/c.zoom.value,(e.clientY-box.top)/c.zoom.value];}
  function snap(p:[number,number]):[number,number]{if(!options.snap)return p;return p.map((v,i)=>{let next=Math.round(v/10)*10;for(const g of c.project.value?.manifest.guides??[])if(g.axis===(i?'horizontal':'vertical')&&Math.abs(v-g.position)<6/c.zoom.value)next=g.position;return next;}) as [number,number];}
  function drawSelection(){const canvas=c.overlay.value,p=c.project.value;if(!canvas||!p)return;canvas.width=p.manifest.width;canvas.height=p.manifest.height;const s=p.selection;if(!s)return;const ctx=canvas.getContext('2d')!,image=ctx.createImageData(s.width,s.height),w=s.width;
    for(let y=0;y<s.height;y++)for(let x=0;x<w;x++){const i=y*w+x,v=s.data[i];if(!v)continue;const edge=x===0||y===0||x===w-1||y===s.height-1||!s.data[i-1]||!s.data[i+1]||!s.data[i-w]||!s.data[i+w];image.data[i*4]=edge?255:65;image.data[i*4+1]=edge?255:150;image.data[i*4+2]=255;image.data[i*4+3]=edge?210:Math.round(v*.1);}ctx.putImageData(image,0,0);
  }
  function cancel(){drag=undefined;c.painting.value=applying;cropBox.value=undefined;drawSelection();}
  function drawDrag(d:Drag){drawSelection();const ctx=c.overlay.value?.getContext('2d');if(!ctx)return;ctx.lineWidth=1/c.zoom.value;ctx.strokeStyle='#ffffff';ctx.setLineDash([5/c.zoom.value,4/c.zoom.value]);ctx.fillStyle='rgba(76,156,230,.13)';const [x,y]=d.start,[dx,dy]=d.current,w=dx-x,h=dy-y;
    if(['marquee','crop','shape'].includes(d.tool)){ctx.beginPath();if((d.tool==='marquee'&&options.marquee==='ellipse')||(d.tool==='shape'&&options.shape==='Ellipse'))ctx.ellipse(x+w/2,y+h/2,Math.abs(w)/2,Math.abs(h)/2,0,0,Math.PI*2);else if(d.tool==='shape'&&options.shape==='Line'){ctx.moveTo(x,y);ctx.lineTo(dx,dy);}else ctx.rect(x,y,w,h);ctx.fill();ctx.stroke();}
    else if(d.tool==='lasso'){ctx.beginPath();d.points.forEach((p,i)=>i?ctx.lineTo(p[0],p[1]):ctx.moveTo(p[0],p[1]));ctx.closePath();ctx.fill();ctx.stroke();}
    else if(d.tool==='move'){const b=bounds(d.transform??d.row!.transform);ctx.strokeRect(b.x+dx-x,b.y+dy-y,b.w,b.h);}
    else {ctx.setLineDash([]);ctx.lineWidth=d.settings.size??2;ctx.globalAlpha=.55;ctx.lineCap='round';ctx.strokeStyle=c.color.value;ctx.beginPath();d.points.forEach((p,i)=>i?ctx.lineTo(p[0],p[1]):ctx.moveTo(p[0],p[1]));ctx.stroke();ctx.globalAlpha=1;}
  }
  async function sample(p:ViewerProject,merged=true){if(merged){if(!c.canvas.value)throw new Error('asset');return pngBytes(c.canvas.value);}const row=c.selected.value;if(!row?.imageFile)throw new Error('asset');const surface=await placedImage(p.urls['images/'+row.imageFile],row.transform,p.manifest.width,p.manifest.height);try{return await pngBytes(surface);}finally{surface.width=surface.height=1;}}
  function start(e:PointerEvent):boolean {
    const p=c.project.value;if(!p||e.button!==0||!c.artboard.value?.contains(e.target as Node))return false;
    const key=c.tool.value;if(key==='pan')return false;if(!c.editable.value)return true;const at=point(e),row=c.selected.value;
    if(key==='zoom'){c.scale(e.altKey?.8:1.25);return true;}
    if(key==='eyedropper'){void instant(()=>pick(at,e.altKey));return true;}
    if(key==='clone'&&e.altKey){cloneSource.value=at;return true;}
    if(key==='wand'){void instant(()=>wand(at));return true;}
    if(key==='bucket'){void instant(()=>bucket(at));return true;}
    if(key==='type'){const hit=[...p.analysis.rows].reverse().find(l=>l.text&&l.effectiveVisible&&(()=>{const b=bounds(l.transform);return at[0]>=b.x&&at[1]>=b.y&&at[0]<=b.x+b.w&&at[1]<=b.y+b.h;})());if(hit){select(hit);openStyle('text');}else openStyle('text',at);return true;}
    if(key==='move'&&(options.autoSelect||e.ctrlKey)){const hit=[...p.analysis.rows].reverse().find(l=>l.effectiveVisible&&l.imageFile&&(()=>{const b=bounds(l.transform);return at[0]>=b.x&&at[1]>=b.y&&at[0]<=b.x+b.w&&at[1]<=b.y+b.h;})());if(hit)select(hit,e as unknown as MouseEvent);}
    if(['move','brush','eraser','healing','clone','smear','gradient'].includes(key)&&!c.selected.value)return true;
    if(['brush','eraser','healing','clone','smear','gradient'].includes(key)&&!(c.paintTarget.value==='mask'?row?.maskFile:row?.imageFile))return true;
    if(key==='clone'&&!cloneSource.value){c.error.value='source';return true;}
    const settings={size:c.brushSize.value,opacity:c.brushOpacity.value/100,hardness:options.hardness/100,spacing:options.spacing/100,pressure:options.pressure,color:colors(c.color.value),background:colors(background.value),symmetry:options.symmetry,sectors:options.sectors,mode:key==='smear'?options.smear:key,source:cloneSource.value,radial:options.radial,reverse:options.reverse,transparent:options.transparent};
    drag={p:clone(p),params:clone(options),target:c.paintTarget.value,transform:selectionTransform.value?clone(selectionTransform.value):undefined,row:c.selected.value?clone(c.selected.value):undefined,pointer:e.pointerId,tool:key,start:snap(at),current:snap(at),points:[[...at,e.pointerType==='pen'?e.pressure:1]],settings,ids:[...ids.value],handle:(e.target as HTMLElement).getAttribute?.('data-handle')??undefined};
    c.painting.value=true;c.stage.value?.setPointerCapture(e.pointerId);drawDrag(drag);return true;
  }
  async function instant(action:()=>Promise<unknown>){applying=true;c.painting.value=true;try{await action();}catch{c.error.value='asset';}finally{applying=false;c.painting.value=false;}}
  async function wand(at:[number,number]){const p=c.project.value;if(!p)return;await c.execute({kind:'selection',action:'wand',start:at,combine:options.combine,tolerance:options.tolerance,contiguous:options.contiguous,png:await sample(p,options.sampleAll)},p);}
  // Keep all sampling paths revision-bound, including asynchronous PNG encoding.

  function move(e:PointerEvent){if(!drag||drag.pointer!==e.pointerId)return false;drag.current=snap(point(e));if(drag.points.length<10000)drag.points.push([...drag.current,e.pointerType==='pen'?e.pressure:1]);drawDrag(drag);return true;}
  async function end(e:PointerEvent){const d=drag;if(!d||d.pointer!==e.pointerId)return false;drag=undefined;applying=true;c.painting.value=true;drawSelection();if(!valid(d.p)){applying=false;c.painting.value=false;return true;}const [x,y]=d.start,[ex,ey]=d.current;
    try{
      if(d.tool==='move'&&d.row){const rows=roots(d.p,d.ids.length?d.ids:[d.row.id]);if(d.handle==='rotate'){const t=d.transform!,angle=(Math.atan2(ey-t.origin[1]-t.size[1]/2,ex-t.origin[0]-t.size[0]/2)-Math.atan2(y-t.origin[1]-t.size[1]/2,x-t.origin[0]-t.size[0]/2))*180/Math.PI;await c.execute({kind:d.ids.length>1||d.row.isGroup?'transformLayers':'transform',ids:rows,id:d.row.id,field:'rotation',value:t.rotation+angle},d.p);}
        else if(d.handle){const t=d.transform!,local=toLocal(d.current,t,t.size[0],t.size[1]),w=Math.max(1,local[0]),h=e.shiftKey?w*t.size[1]/t.size[0]:Math.max(1,local[1]);await c.execute({kind:d.ids.length>1||d.row.isGroup?'transformLayers':'transform',ids:rows,id:d.row.id,field:'size',value:[w,h]},d.p);}
        else if(ex!==x||ey!==y)await c.execute({kind:'moveLayers',ids:rows,delta:[ex-x,ey-y]},d.p);}
      else if(d.tool==='marquee'||d.tool==='lasso')await c.execute({kind:'selection',action:d.tool==='lasso'?'lasso':d.params.marquee,start:d.start,end:d.current,points:d.points.map(v=>v.slice(0,2)),combine:e.shiftKey?'add':e.altKey?'subtract':d.params.combine},d.p);
      else if(d.tool==='crop'){cropBox.value={x:Math.floor(Math.min(x,ex)),y:Math.floor(Math.min(y,ey)),w:Math.max(1,Math.round(Math.abs(ex-x))),h:Math.max(1,Math.round(Math.abs(ey-y)))};drawDrag(d);}
      else if(d.tool==='shape'){const w=Math.max(1,Math.abs(ex-x)),h=Math.max(1,Math.abs(ey-y)),s={kind:d.params.shape,...Object.fromEntries(d.settings.color.map((v:number,i:number)=>[['red','green','blue'][i],v/255])),cornerRadius:d.params.corner,lineWidth:d.params.lineWidth,start:[x<=ex?0:1,y<=ey?0:1],end:[x<=ex?1:0,y<=ey?1:0]};await c.execute({kind:'styled',id:undefined,type:'shape',origin:[Math.min(x,ex),Math.min(y,ey)],style:s,png:await renderShape(s,w,h),name:labels.value.shape,parentID:d.row?.isGroup?d.row.id:d.row?.parentID},d.p);}
      else if(d.tool==='gradient')await c.execute({kind:'gradient',id:d.row!.id,target:d.target,settings:{...d.settings,mode:undefined,points:[d.start,d.current]}},d.p);
      else await c.execute({kind:'stroke',id:d.row!.id,target:d.target,settings:{...d.settings,points:d.points}},d.p);
    }catch(error){c.error.value=(error as Error).message==='limit'?'limit':'invalid';}finally{applying=false;c.painting.value=false;}return true;
  }
  async function pick(at:[number,number],back=false){const p=c.project.value;if(!p||!c.canvas.value)return;const surface=options.sampleAll?c.canvas.value:await placedImage(p.urls['images/'+c.selected.value?.imageFile],c.selected.value!.transform,p.manifest.width,p.manifest.height);try{const px=surface.getContext('2d')!.getImageData(Math.max(0,Math.min(surface.width-1,Math.floor(at[0]))),Math.max(0,Math.min(surface.height-1,Math.floor(at[1]))),1,1).data,value='#'+[...px.slice(0,3)].map(n=>n.toString(16).padStart(2,'0')).join('');if(back)background.value=value;else c.color.value=value;}finally{if(surface!==c.canvas.value)surface.width=surface.height=1;}}
  async function bucket(at:[number,number]){const p=c.project.value;if(!p||!c.selected.value?.imageFile)return;try{await c.execute({kind:'bucket',id:c.selected.value.id,target:c.paintTarget.value,point:at,png:await sample(p,options.sampleAll),settings:{color:colors(c.color.value),opacity:c.brushOpacity.value/100,tolerance:options.tolerance,contiguous:options.contiguous}},p);}catch{c.error.value='asset';}}
  function selection(action:string){return c.execute({kind:'selection',action,amount:options.selectionAmount});}
  function fill(action='fill'){return c.execute({kind:action,id:c.selected.value?.id,target:c.paintTarget.value,settings:{color:colors(c.color.value),opacity:c.brushOpacity.value/100}});}
  function applyCrop(){const box=cropBox.value;if(box){cropBox.value=undefined;return c.execute({kind:'canvas',x:box.x,y:box.y,width:box.w,height:box.h});}}
  function cropSelection(){const p=c.project.value,s=p?.selection;if(!s){c.error.value='selection';return;}const box=maskBounds(s.data,s.width,s.height);if(!box){c.error.value='selection';return;}return c.execute({kind:'canvas',x:box.x,y:box.y,width:box.w,height:box.h});}
  function openSize(kind:string){const p=c.project.value;if(!p)return;size.width=p.manifest.width;size.height=p.manifest.height;modal.value=kind;}
  function applySize(){const p=c.project.value;if(!p)return;const kind=modal.value;modal.value='';if(kind==='imageSize')return c.execute({kind,width:size.width,height:size.height,nearest:size.nearest});const f=size.anchor==='topLeft'?0:size.anchor==='middle'?.5:1;return c.execute({kind:'canvas',width:size.width,height:size.height,x:(p.manifest.width-size.width)*f,y:(p.manifest.height-size.height)*f});}
  function trim(){const surface=c.canvas.value;if(!surface)return;const pixels=surface.getContext('2d')!.getImageData(0,0,surface.width,surface.height).data,alpha=Uint8Array.from({length:surface.width*surface.height},(_,i)=>pixels[i*4+3]),box=maskBounds(alpha,surface.width,surface.height);if(box)return c.execute({kind:'canvas',x:box.x,y:box.y,width:box.w,height:box.h});}
  function align(operation:string){return c.execute({kind:'arrange',ids:ids.value.length?ids.value:[c.selected.value?.id].filter(Boolean),operation,reference:options.reference,keyID:c.selected.value?.id});}
  function group(){return c.execute({kind:'group',ids:ids.value,name:labels.value.group});}
  function duplicate(){const p=c.project.value;if(!p)return;return c.execute({kind:'batch',operations:roots(p,ids.value).map(id=>({kind:'duplicateTree',id,copySuffix:labels.value.copySuffix}))});}
  function remove(){const p=c.project.value;if(!p)return;return c.execute({kind:'batch',operations:roots(p,ids.value).map(id=>({kind:'delete',id}))});}
  function merge(flatten=false){return instant(()=>performMerge(flatten));}
  async function performMerge(flatten=false){const p=c.project.value;if(!p||!c.canvas.value)return;const chosen=flatten?p.manifest.layers.filter(l=>!l.parentID).map(l=>l.id):roots(p,ids.value);if(!chosen.length)return;
    const include=new Set(chosen);for(let n=0;n<64;n++)for(const l of p.manifest.layers)if(l.parentID&&include.has(l.parentID))include.add(l.id);
    if(!flatten&&p.manifest.layers.some(l=>include.has(l.id)&&((l.blendMode??'Normal')!=='Normal'||l.maskSourceID&&!include.has(l.maskSourceID)))){c.error.value='unsupported';return;}
    const surface=flatten?c.canvas.value:makeCanvas(p.manifest.width,p.manifest.height);let renderer:ReturnType<typeof createPreviewRenderer>|undefined;
    try{if(!flatten){renderer=createPreviewRenderer();const selected=clone(p);selected.manifest.layers=selected.manifest.layers.filter(l=>include.has(l.id));selected.analysis.rows=selected.analysis.rows.filter(l=>include.has(l.id)).map(l=>{let opacity=l.opacity??1;let parent=p.analysis.rows.find(v=>v.id===l.parentID);for(let n=0;parent&&include.has(parent.id)&&n<64;n++){opacity*=parent.opacity??1;parent=p.analysis.rows.find(v=>v.id===parent!.parentID);}return {...l,parentID:include.has(l.parentID??'')?l.parentID:undefined,effectiveOpacity:opacity};});await renderer.render(selected,surface,()=>{});}await c.execute({kind:'merge',ids:chosen,png:await pngBytes(surface),name:labels.value.merge},p);}catch{c.error.value='asset';}finally{renderer?.dispose();if(surface!==c.canvas.value)surface.width=surface.height=1;}
  }
  function setLock(field:string,value:boolean){return c.execute({kind:'lock',id:c.selected.value?.id,field,value});}
  function addGuide(){const p=c.project.value;if(p)return c.execute({kind:'guides',guides:[...(p.manifest.guides??[]),{id:crypto.randomUUID().toUpperCase(),axis:options.guideAxis,position:options.guidePosition}]});}
  function clearGuides(){return c.execute({kind:'guides',guides:[]});}
  function openStyle(kind='text',at?:[number,number]){const p=c.project.value;if(!p)return;styleOwner=clone(p);const candidate=at?undefined:c.selected.value,row=candidate?.[kind as 'text'|'shape']?candidate:undefined;styledID=row?.id;styleOrigin=at??row?.transform.origin??[0,0];modal.value=kind;
    if(kind==='text'){const col=colors(c.color.value);Object.assign(text,{content:row?.text?.content??'',fontName:'ArialMT',fontSize:48,red:col[0]/255,green:col[1]/255,blue:col[2]/255,alignment:'Left',tracking:0,leading:0,boxSize:row?.transform.size??[Math.max(16,Math.min(480,p.manifest.width)),Math.max(16,Math.min(240,p.manifest.height))],colorRuns:[],fontRuns:[]},row?.text?clone(row.text):{});originalContent=text.content;}
    else Object.assign(shape,{kind:options.shape,red:colors(c.color.value)[0]/255,green:colors(c.color.value)[1]/255,blue:colors(c.color.value)[2]/255,cornerRadius:options.corner,lineWidth:options.lineWidth,start:[0,0],end:[1,1]},row?.shape?clone(row.shape):{});
    size.width=row?.transform.size[0]??200;size.height=row?.transform.size[1]??200;void updatePreview();
  }
  function rememberRange(){range=[textArea.value?.selectionStart??0,textArea.value?.selectionEnd??0];}
  function styleRange(which:string){if(text.content!==originalContent){text.colorRuns=remapRuns(text.colorRuns,originalContent,text.content);text.fontRuns=remapRuns(text.fontRuns,originalContent,text.content);originalContent=text.content;}const [start,end]=range;if(end<=start)return;if(which==='color')text.colorRuns=rangeStyle(text.colorRuns,start,end,{red:text.red,green:text.green,blue:text.blue});else text.fontRuns=rangeStyle(text.fontRuns,start,end,{fontName:text.fontName});void updatePreview();}
  function editedText(){const s=clone(text);if(s.content!==originalContent){s.colorRuns=remapRuns(s.colorRuns,originalContent,s.content);s.fontRuns=remapRuns(s.fontRuns,originalContent,s.content);}return s;}
  async function applyStyle(){const kind=modal.value,p=styleOwner;if(!valid(p))return;const own=++previewEpoch;previewBusy.value=true;try{const s=kind==='text'?editedText():clone(shape),png=kind==='text'?await renderText(s):await renderShape(s,size.width,size.height);if(!valid(p)||own!==previewEpoch||modal.value!==kind)return;closeModal();await c.execute({kind:'styled',id:styledID,type:kind,style:s,png,origin:styleOrigin,name:kind==='text'?s.content.slice(0,64):labels.value.shape},p);}catch(e){c.error.value=(e as Error).message==='limit'?'limit':'invalid';}finally{if(own===previewEpoch)previewBusy.value=false;}}
  function openFilter(){if(!c.selected.value?.imageFile)return;modal.value='filter';styleOwner=clone(c.project.value!);void updatePreview();}
  async function applyFilter(){const p=styleOwner;if(!valid(p))return;closeModal();await c.execute({kind:'filter',id:c.selected.value?.id,filter:filter.kind,settings:clone(filter)},p);}
  async function updatePreview(){const own=++previewEpoch;(previewWorker as Worker|undefined)?.terminate();previewWorker=undefined;previewBusy.value=true;try{let png:Uint8Array;
      if(modal.value==='text')png=await renderText(editedText());else if(modal.value==='shape')png=await renderShape(clone(shape),size.width,size.height);
      else if(modal.value==='filter'){const p=c.project.value,row=c.selected.value;if(!p||!row?.imageFile)return;const response=await fetch(p.urls['images/'+row.imageFile]),bitmap=await createImageBitmap(await response.blob()),surface=makeCanvas(bitmap.width,bitmap.height);surface.getContext('2d')!.drawImage(bitmap,0,0);bitmap.close();const image=surface.getContext('2d')!.getImageData(0,0,surface.width,surface.height);surface.width=surface.height=1;
        const result=await new Promise<ImageData>((resolve,reject)=>{const worker=previewWorker=new Worker(new URL('./editor-worker.ts',import.meta.url),{type:'module'});worker.onmessage=e=>e.data.error?reject(new Error(e.data.error)):resolve(new ImageData(e.data.result.data,e.data.result.width,e.data.result.height));worker.onerror=()=>reject(new Error('asset'));worker.postMessage({image:{width:image.width,height:image.height,data:image.data},placement:clone(row.transform),selection:p.selection?{...p.selection,data:new Uint8Array(p.selection.data)}:null,kind:filter.kind,settings:clone(filter)},[image.data.buffer]);});if(own!==previewEpoch)return;const output=makeCanvas(result.width,result.height);output.getContext('2d')!.putImageData(result,0,0);png=await pngBytes(output);output.width=output.height=1;
      }else return;if(own!==previewEpoch)return;if(previewBlob)URL.revokeObjectURL(previewBlob);previewBlob=URL.createObjectURL(new Blob([new Uint8Array(png).buffer],{type:'image/png'}));previewURL.value=previewBlob;
    }catch(e){if(own===previewEpoch)c.error.value=(e as Error).message==='selection'?'selection':'asset';}finally{if(own===previewEpoch){previewBusy.value=false;(previewWorker as Worker|undefined)?.terminate();previewWorker=undefined;}}}
  function filterParameter(op:Record<string,any>){if(op.path){let root=filter[op.field];for(const k of op.path.slice(0,-1))root=root[k];root[op.path.at(-1)]=op.value;}else filter[op.field]=op.value;}
  function closeModal(){modal.value='';previewEpoch++;(previewWorker as Worker|undefined)?.terminate();previewWorker=undefined;previewBusy.value=false;if(previewBlob)URL.revokeObjectURL(previewBlob);previewBlob=undefined;previewURL.value='';}
  let clipboardQueue=Promise.resolve(),clipboardCount=0;const clipboardBusy=ref(false);
  function clipboard(action:string){const documentID=c.project.value?.id,rowID=c.selected.value?.id;clipboardCount++;clipboardBusy.value=true;clipboardQueue=clipboardQueue.then(()=>{if(c.project.value?.id===documentID)return instant(()=>performClipboard(action,rowID));}).catch(()=>{c.error.value='asset';}).finally(()=>{clipboardBusy.value=--clipboardCount>0;});return clipboardQueue;}
  async function performClipboard(action:string,rowID?:string){const p=c.project.value,row=p?.analysis.rows.find(l=>l.id===rowID);if(!p)return;try{if(action==='paste'){const result=await window.editor.clipboard(p.id,p.revision,'paste');if(valid(p))await c.receive(result);return;}let surface=c.canvas.value;if(action!=='copyMerged'&&row?.imageFile)surface=await placedImage(p.urls['images/'+row.imageFile],row.transform,p.manifest.width,p.manifest.height);if(!surface)return;
      const copy=makeCanvas(surface.width,surface.height),ctx=copy.getContext('2d')!;ctx.drawImage(surface,0,0);if(surface!==c.canvas.value)surface.width=surface.height=1;
      if(p.selection){const image=ctx.getImageData(0,0,copy.width,copy.height);for(let y=0;y<copy.height;y++)for(let x=0;x<copy.width;x++)image.data[(y*copy.width+x)*4+3]*=selectionCoverage(p.selection,[x+.5,y+.5]);ctx.putImageData(image,0,0);}
      let output=copy;const b=p.selection?maskBounds(p.selection.data,p.selection.width,p.selection.height):undefined;if(b){output=makeCanvas(b.w,b.h);output.getContext('2d')!.drawImage(copy,b.x,b.y,b.w,b.h,0,0,b.w,b.h);}const png=await pngBytes(output);copy.width=copy.height=1;if(output!==copy)output.width=output.height=1;
      const result=await window.editor.clipboard(p.id,p.revision,'copy',png);if(result.error){c.error.value=result.error;return;}if(action==='cut'&&valid(p))await c.execute({kind:'clear',id:row?.id,target:c.paintTarget.value,settings:{}},p);
    }catch{c.error.value='asset';}}
  function key(e:KeyboardEvent){if(e.isComposing)return;const input=(e.target as HTMLElement)?.closest('input,textarea,select,[contenteditable]');if(e.key==='Escape'){cancel();closeModal();return;}if(input)return;const k=e.key.toLowerCase();if(modal.value)return;if(c.painting.value&&!(clipboardBusy.value&&e.ctrlKey&&['c','v','x'].includes(k)))return;
    if(!e.ctrlKey&&!e.metaKey&&!e.altKey&&!c.painting.value){const found=TOOL_LIST.find(v=>TOOL_KEYS[v].toLowerCase()===k);if(found){c.tool.value=found;e.preventDefault();return;}if(k==='x'){[c.color.value,background.value]=[background.value,c.color.value];return;}if(k==='d'){c.color.value='#000000';background.value='#ffffff';return;}if(k==='delete'||k==='backspace'){e.preventDefault();if(c.project.value?.selection)fill('clear');else remove();}}
    if(e.ctrlKey){if(k==='a'){e.preventDefault();selection('all');}if(k==='d'){e.preventDefault();selection('none');}if(k==='i'&&e.shiftKey){e.preventDefault();selection('invert');}if(k==='g'){e.preventDefault();if(e.shiftKey)c.execute({kind:'ungroup'});else group();}if(k==='c'){e.preventDefault();clipboard(e.shiftKey?'copyMerged':'copy');}if(k==='x'){e.preventDefault();clipboard('cut');}if(k==='v'){e.preventDefault();clipboard('paste');}}
    if(e.key==='Enter'&&cropBox.value){e.preventDefault();applyCrop();}
  }
  const commands:Record<string,()=>unknown>={selectAll:()=>selection('all'),deselect:()=>selection('none'),invertSelection:()=>selection('invert'),expandSelection:()=>selection('expand'),contractSelection:()=>selection('contract'),featherSelection:()=>selection('feather'),fill:()=>fill(),clear:()=>fill('clear'),selectionMask:()=>c.execute({kind:'selectionMask'}),cropSelection,canvasSize:()=>openSize('canvasSize'),imageSize:()=>openSize('imageSize'),trim,filter:openFilter,group,ungroup:()=>c.execute({kind:'ungroup'}),duplicate,delete:remove,merge:()=>merge(),flatten:()=>merge(true),rasterize:()=>c.execute({kind:'rasterize'}),applyMask:()=>c.execute({kind:'applyMask'}),text:()=>openStyle('text'),shape:()=>openStyle('shape'),copy:()=>clipboard('copy'),copyMerged:()=>clipboard('copyMerged'),cut:()=>clipboard('cut'),paste:()=>clipboard('paste'),flipCanvasH:()=>c.execute({kind:'flipCanvas',axis:'horizontal'}),flipCanvasV:()=>c.execute({kind:'flipCanvas',axis:'vertical'}),grid:()=>{options.grid=!options.grid;},snap:()=>{options.snap=!options.snap;}};
  return {labels,ids,background,options,modal,size,text,shape,filter,filters:FILTERS,previewURL,previewBusy,clipboardBusy,textArea,cloneSource,cropBox,selectedRows,selectedRect,selectionTransform,lock,select,start,move,end,cancel,selection,fill,applyCrop,cropSelection,openSize,applySize,trim,align,group,duplicate,remove,merge,setLock,addGuide,clearGuides,openStyle,rememberRange,styleRange,applyStyle,openFilter,applyFilter,filterParameter,updatePreview,closeModal,clipboard,key,commands,drawSelection};
}
